baseURL = "http://aviitala.com"
title = "ANTTI VIITALA"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
enableRobotsTXT = true
enableGitInfo = true

# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Antti Viitala"
license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Antti Viitala personal portfolio site"
keywords = "blog,developer,personal"
info = ["DevOps", "Cloud Architecture", "Professional googler"]
avatarURL = "images/avatar.png"
favicon_16 = "images/favicon-16x16.png"
favicon_32 = "images/favicon-32x32.png"
#gravatar = "john.doe@example.com"
dateFormat = "2006-01-02"
since = 2022
manifest =  "site.webmanifest"

# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/Antvirf/antvirf.github.io/commit"
colorScheme = "auto" # auto / dark / light
hideColorSchemeToggle = false
maxSeeAlsoItems = 5

# Custom CSS
customCSS = ["custom_style.css"]
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

[permalinks]
posts = '/posts/:slugorfilename' #-:year:month:day'

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
[params.goatCounter]
code = "aviitala"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to use Application Insights(https://azure.com/) for analytics, add this section
# [params.applicationInsights]
# connectionString = "connectionString"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = [
  "'self'",
  "http://aviitala.goatcounter.com",
  "https://aviitala.com",
  "https://github.com",
  "https://raw.githubusercontent.com",
  "https://img.shields.io",
  "https://sonarcloud.io",
  "https://dl.circleci.com"
  ]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = [
  "'self'",
  "'unsafe-inline'",
  "https://www.google-analytics.com",
  "https://cdn.jsdelivr.net/",
  "http://gc.zgo.at"
]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/Antvirf/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/anttiviitala/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "CV"
weight = 1
url = "cv/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

# [[languages.en.menu.main]]
# name = "Contact me"
# weight = 5
# url = "contact/"

# [languages.fi]
# languageName = ":finland:"

# [languages.fi.params]
# author = "João Ninguém"
# info = "Full Stack DevOps e Mágico"
# description = "Sítio pessoal de João Ninguém"
# keywords = "blog,desenvolvedor,pessoal"

# [[languages.fi.menu.main]]
# name = "CV"
# weight = 1
# url = "about/"

# [[languages.fi.menu.main]]
# name = "Blogi"
# weight = 2
# url = "posts/"

# [[languages.fi.menu.main]]
# name = "Projektit"
# weight = 3
# url = "projects/"

# [[languages.fi.menu.main]]
# name = "Ota yhteyttä"
# weight = 5
# url = "contact/"
